version: "3.7"
services:
  laravel:
    env_file:
      - ./laravel/.env
    build:
      context: ./laravel/vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.0/app
    container_name: laravel
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 0
    volumes:
      - './laravel:/var/www/html'
    networks:
      - app_network
  mysql:
    env_file:
      - ./laravel/.env
    image: 'mysql:8.0'
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './mysql/storage:/var/lib/mysql'
    networks:
      - app_network
    ports:
      - "3306:3306"
  app:
    build:
      context: ./app
    container_name: app
    networks:
      - app_network
    volumes:
      - ./app/app:/app
    environment:
      - APACHE_SERVER_NAME=patchcablemgr.com
    restart: on-failure

  database:
    image: mysql
    container_name: database
    networks:
      - app_network
    ports:
      - "3307:3306"
    volumes:
      - ./database/storage:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=pcm
      - MYSQL_USER=pcmuser
      - MYSQL_PASSWORD=ChangeMe7492#&!
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: on-failure

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - app_network
    restart: always
    ports:
      - 8080:8080
    restart: on-failure

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/cert:/etc/ssl/certs
      - ./nginx/key:/etc/ssl/private
    environment:
      - SUBJECT_ALTERNATE_NAME=pcm.lcl
      - SUBJECT_ALTERNATE_IP=10.0.0.100
    restart: on-failure
networks:
  app_network:
