#!/bin/bash

sudo git -C /home/garrett/pcm_infra/ pull
sudo php /home/garrett/pcm_infra/laravel/vendor/bin/sail up --build
sudo php /home/garrett/pcm_infra/laravel/vendor/bin/envoy run --path=/home/garrett/pcm_infra/laravel/Envoy.blade.php deploy
